import json
import random
data = []

# === 1. TURKCE KOD ACIKLAMA (10 ornek) ===
code_explanations = [
    {
        "instruction": "Python'da list comprehension nedir? Orneklerle acikla.",
        "response": "List comprehension, Python'da listeleri tek satirda olusturmanin kisa ve okunabilir bir yoludur.\n\nTemel sozdizimi:\n```python\n[ifade for eleman in iterable if kosul]\n```\n\nOrnekler:\n\n1. Basit bir liste olusturma:\n```python\nsquares = [i**2 for i in range(10)]\n# Sonuc: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]\n```\n\n2. Kosullu filtreleme:\n```python\neven_squares = [i**2 for i in range(10) if i % 2 == 0]\n# Sonuc: [0, 4, 16, 36, 64]\n```\n\n3. Ic ice donguler:\n```python\npairs = [(x, y) for x in range(3) for y in range(3)]\n```\n\nList comprehension, okunabilir ve performansli kod yazmani saglar. Ancak cok karmasik ifadelerde normal for dongusu daha okunabilir olabilir."
    },
    {
        "instruction": "Python'da generator nedir? yield anahtar kelimesini acikla.",
        "response": "Generator, Python'da lazy evaluation yapan ozel bir fonksiyon turudur. Normal fonksiyonlar tum sonucu bir kerede dondururken, generator her cagirida bir sonraki degeri uretir.\n\nyield anahtar kelimesi:\n- return yerine yield kullanilir\n- Fonksiyonun durumunu korur\n- Her next() cagrisinda kaldigi yerden devam eder\n\nOrnek:\n```python\ndef count_up_to(n):\n    i = 1\n    while i <= n:\n        yield i\n        i += 1\n\nfor num in count_up_to(5):\n    print(num)\n```\n\nNeden generator kullanilir?\n1. Bellek tasarrufu: Tum listeyi hafizada tutmaz\n2. Buyuk veri setleri: Milyonlarca satiri tek tek isleyebilirsin\n3. Sonsuz diziler: Fibonacci, asal sayilar gibi\n\nPratik ornek - buyuk dosya okuma:\n```python\ndef read_large_file(file_path):\n    with open(file_path, 'r') as f:\n        for line in f:\n            yield line.strip()\n```"
    },
    {
        "instruction": "Python'da *args ve **kwargs nedir?",
        "response": "*args ve **kwargs, fonksiyonlara degisken sayida arguman gecirmek icin kullanilir.\n\n*args - Pozisyonel argumanlar (tuple olarak gelir):\n```python\ndef toplam(*args):\n    return sum(args)\n\nprint(toplam(1, 2, 3))        # 6\nprint(toplam(1, 2, 3, 4, 5))  # 15\n```\n\n**kwargs - Isimli argumanlar (dict olarak gelir):\n```python\ndef profil(**kwargs):\n    for key, value in kwargs.items():\n        print(f\"{key}: {value}\")\n\nprofil(isim=\"Ali\", yas=25, sehir=\"Istanbul\")\n```\n\nIkisini birlikte kullanma:\n```python\ndef advanced_func(required, *args, **kwargs):\n    print(f\"Zorunlu: {required}\")\n    print(f\"Ekstra args: {args}\")\n    print(f\"Ekstra kwargs: {kwargs}\")\n```\n\nSiralama kurali: def func(normal, *args, **kwargs)"
    },
    {
        "instruction": "Python'da decorator nedir? Detayli acikla.",
        "response": "Decorator, bir fonksiyonun davranisini degistiren veya genisleten bir fonksiyondur.\n\nBasit decorator:\n```python\ndef my_decorator(func):\n    def wrapper(*args, **kwargs):\n        print(\"Fonksiyon calismadan once\")\n        result = func(*args, **kwargs)\n        print(\"Fonksiyon calistiktan sonra\")\n        return result\n    return wrapper\n\n@my_decorator\ndef say_hello(name):\n    print(f\"Merhaba {name}!\")\n\nsay_hello(\"Ali\")\n```\n\nParametreli decorator:\n```python\ndef repeat(n):\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            for _ in range(n):\n                func(*args, **kwargs)\n        return wrapper\n    return decorator\n\n@repeat(3)\ndef greet():\n    print(\"Merhaba!\")\n```\n\nPratik kullanimlar:\n- Loglama\n- Yetki kontrolu\n- Caching (functools.lru_cache)\n- Performans olcumu"
    },
    {
        "instruction": "Python'da async/await nedir?",
        "response": "Asenkron programlama, uzun suren islemleri beklerken diger isleri yapabilmeni saglar.\n\nTemel kavramlar:\n- async def: asenkron fonksiyon tanimlar\n- await: bir asenkron islemin bitmesini bekler\n- asyncio.run(): ana coroutine'i calistirir\n\n```python\nimport asyncio\n\nasync def fetch_data(name, delay):\n    print(f\"{name} basladi\")\n    await asyncio.sleep(delay)\n    print(f\"{name} bitti\")\n    return f\"{name} sonucu\"\n\nasync def main():\n    results = await asyncio.gather(\n        fetch_data(\"API-1\", 1),\n        fetch_data(\"API-2\", 2),\n        fetch_data(\"API-3\", 1),\n    )\n    print(results)\n\nasyncio.run(main())\n```\n\nNe zaman kullanilir: Web scraping, API cagrilari, veritabani sorgulari\nNe zaman KULLANILMAZ: CPU-yogun islemler (multiprocessing kullan)"
    },
    {
        "instruction": "Python'da context manager nedir?",
        "response": "Context manager, kaynaklarin guvenli sekilde acilip kapatilmasini saglayan bir yapidir.\n\n```python\n# KOTU - dosya acik kalabilir\nf = open('file.txt', 'r')\ndata = f.read()\nf.close()\n\n# IYI - with ile otomatik kapanir\nwith open('file.txt', 'r') as f:\n    data = f.read()\n```\n\nKendi context manager'ini yazma:\n```python\nclass DatabaseConnection:\n    def __init__(self, host):\n        self.host = host\n    def __enter__(self):\n        self.conn = create_connection(self.host)\n        return self.conn\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        self.conn.close()\n        return False\n\nwith DatabaseConnection('localhost') as conn:\n    conn.execute('SELECT * FROM users')\n```\n\ncontextlib ile daha kolay:\n```python\nfrom contextlib import contextmanager\n\n@contextmanager\ndef timer():\n    import time\n    start = time.time()\n    yield\n    print(f\"Sure: {time.time() - start:.2f} saniye\")\n```"
    },
    {
        "instruction": "Python'da class inheritance nasil calisir?",
        "response": "Kalitim, bir sinifin baska bir sinifin ozelliklerini miras almasidir.\n\n```python\nclass Animal:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def speak(self):\n        raise NotImplementedError\n\nclass Dog(Animal):\n    def speak(self):\n        return f\"{self.name}: Hav hav!\"\n\nclass Cat(Animal):\n    def speak(self):\n        return f\"{self.name}: Miyav!\"\n\ndog = Dog(\"Karabas\", 3)\nprint(dog.speak())  # Karabas: Hav hav!\n```\n\nsuper() kullanimi:\n```python\nclass Puppy(Dog):\n    def __init__(self, name, age, toy):\n        super().__init__(name, age)\n        self.toy = toy\n```\n\nCoklu kalitim:\n```python\nclass FlyingAnimal:\n    def fly(self): return \"Ucuyor!\"\n\nclass SwimmingAnimal:\n    def swim(self): return \"Yuzuyor!\"\n\nclass Duck(FlyingAnimal, SwimmingAnimal):\n    pass\n```\n\nBest practice: Composition over inheritance tercih et."
    },
    {
        "instruction": "Python'da error handling nasil yapilir?",
        "response": "Error handling, programdaki hatalari yakalayip uygun sekilde yonetmektir.\n\n```python\ntry:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print(\"Sifira bolunemez!\")\n```\n\nBirden fazla exception:\n```python\ntry:\n    value = int(input(\"Sayi girin: \"))\n    result = 10 / value\nexcept ValueError:\n    print(\"Gecersiz format!\")\nexcept ZeroDivisionError:\n    print(\"Sifira bolunemez!\")\nexcept Exception as e:\n    print(f\"Beklenmeyen hata: {e}\")\n```\n\nelse ve finally:\n```python\ntry:\n    f = open('data.txt', 'r')\n    data = f.read()\nexcept FileNotFoundError:\n    print(\"Dosya bulunamadi!\")\nelse:\n    print(f\"Basariyla okundu: {len(data)} karakter\")\nfinally:\n    print(\"Islem tamamlandi\")\n```\n\nKendi exception sinifi:\n```python\nclass InsufficientFundsError(Exception):\n    def __init__(self, balance, amount):\n        super().__init__(f\"Yetersiz bakiye! Bakiye: {balance}, Istenen: {amount}\")\n```"
    },
    {
        "instruction": "Python'da dataclass nedir?",
        "response": "Dataclass, Python 3.7+ ile gelen, veri tasiyan siniflari hizlica olusturmani saglayan bir decorator'dir.\n\n```python\nfrom dataclasses import dataclass\n\n@dataclass\nclass Student:\n    name: str\n    age: int\n    grade: float\n\n# Otomatik __init__, __repr__, __eq__ olusturulur\nstudent = Student(\"Ali\", 20, 3.5)\nprint(student)  # Student(name='Ali', age=20, grade=3.5)\n```\n\nVarsayilan degerler:\n```python\n@dataclass\nclass Config:\n    host: str = \"localhost\"\n    port: int = 8080\n    debug: bool = False\n```\n\nFrozen (degistirilemez):\n```python\n@dataclass(frozen=True)\nclass Point:\n    x: float\n    y: float\n\np = Point(1.0, 2.0)\np.x = 3.0  # FrozenInstanceError!\n```"
    },
    {
        "instruction": "Python'da lambda fonksiyonlari ne ise yarar?",
        "response": "Lambda, isimsiz tek satirlik fonksiyonlar olusturmak icin kullanilir.\n\nSozdizimi: lambda parametreler: ifade\n\nEn cok kullanildigi yerler:\n\n1. sorted() ile:\n```python\nstudents = [('Ali', 85), ('Ayse', 92), ('Can', 78)]\nsorted_students = sorted(students, key=lambda s: s[1], reverse=True)\n```\n\n2. map() ile:\n```python\nnumbers = [1, 2, 3, 4, 5]\ndoubled = list(map(lambda x: x * 2, numbers))\n```\n\n3. filter() ile:\n```python\nevens = list(filter(lambda x: x % 2 == 0, range(10)))\n```\n\nNe zaman kullanilmamali:\n- Karmasik mantik gerektiginde\n- Ayni lambda birden fazla yerde kullaniliyorsa\n- Okunabilirligi dusuruyorsa"
    },
]

# === 2. BUG BULMA VE DUZELTME (10 ornek) ===
bug_fixes = [
    {
        "instruction": "Bu kodda hata var:\n```python\ndef calculate_average(numbers):\n    total = 0\n    for num in numbers:\n        total += num\n    return total / len(numbers)\n\nresult = calculate_average([])\n```",
        "response": "Hata: Bos liste verildiginde ZeroDivisionError olusur. len(numbers) bos liste icin 0 dondurur.\n\nDuzeltilmis kod:\n```python\ndef calculate_average(numbers):\n    if not numbers:\n        return 0\n    return sum(numbers) / len(numbers)\n```\n\nBest practice: Bos koleksiyon kontrolu her zaman yapilmalidir."
    },
    {
        "instruction": "Bu kodda ne yanlis?\n```python\ndef find_duplicates(lst):\n    duplicates = []\n    for i in lst:\n        if lst.count(i) > 1:\n            duplicates.append(i)\n    return duplicates\n```",
        "response": "Iki sorun var:\n\n1. Performans: list.count() her eleman icin O(n). Toplam O(n^2).\n2. Tekrar: Ayni eleman birden fazla kez eklenir.\n\nDuzeltilmis:\n```python\ndef find_duplicates(lst):\n    seen = set()\n    duplicates = set()\n    for item in lst:\n        if item in seen:\n            duplicates.add(item)\n        seen.add(item)\n    return list(duplicates)\n```\n\nAlternatif:\n```python\nfrom collections import Counter\ndef find_duplicates(lst):\n    return [item for item, count in Counter(lst).items() if count > 1]\n```"
    },
    {
        "instruction": "Bu JavaScript kodundaki hatayi bul:\n```javascript\nfor (var i = 0; i < 5; i++) {\n  setTimeout(function() {\n    console.log(i);\n  }, 1000);\n}\n```",
        "response": "Klasik closure hatasi! 0,1,2,3,4 yerine 5,5,5,5,5 yazdirir. var function-scoped oldugu icin donga bittiginde i=5 olmus olur.\n\nDuzeltme - let kullan:\n```javascript\nfor (let i = 0; i < 5; i++) {\n  setTimeout(function() {\n    console.log(i);  // 0, 1, 2, 3, 4\n  }, 1000);\n}\n```\n\nBest practice: Modern JavaScript'te her zaman let veya const kullan."
    },
    {
        "instruction": "Bu kodda SQL Injection acigi var:\n```python\ndef get_user(username):\n    query = f\"SELECT * FROM users WHERE username = '{username}'\"\n    cursor.execute(query)\n```",
        "response": "SQL Injection acigi! Kullanici girdisi dogrudan SQL'e ekleniyor.\n\nSaldiri ornegi: get_user(\"admin' OR '1'='1\") tum kayitlari dondurur!\n\nDuzeltilmis - Parameterized query:\n```python\ndef get_user(username):\n    cursor.execute(\n        \"SELECT * FROM users WHERE username = ?\",\n        (username,)\n    )\n    return cursor.fetchone()\n```\n\nKural: ASLA string formatting ile SQL yazma. Her zaman parameterized query kullan."
    },
    {
        "instruction": "Bu kodda memory leak var:\n```python\nclass DataProcessor:\n    _cache = {}\n    def process(self, key, data):\n        result = heavy_computation(data)\n        self._cache[key] = result\n        return result\n```",
        "response": "Memory leak: _cache sinif degiskeni, tum instance'lar paylasir ve hic temizlenmiyor.\n\nDuzeltilmis:\n```python\nclass DataProcessor:\n    def __init__(self, max_cache=100):\n        self._cache = {}  # Instance variable\n        self._max_cache = max_cache\n    \n    def process(self, key, data):\n        if key in self._cache:\n            return self._cache[key]\n        result = heavy_computation(data)\n        if len(self._cache) >= self._max_cache:\n            oldest = next(iter(self._cache))\n            del self._cache[oldest]\n        self._cache[key] = result\n        return result\n```\n\nDaha iyi: functools.lru_cache kullan."
    },
    {
        "instruction": "Bu kodda race condition var:\n```python\nimport threading\ncounter = 0\ndef increment():\n    global counter\n    for _ in range(100000):\n        counter += 1\n```",
        "response": "Race condition! counter += 1 atomic bir islem degil. Iki thread ayni anda okuyup yazabilir.\n\nDuzeltilmis - Lock kullan:\n```python\nimport threading\n\ncounter = 0\nlock = threading.Lock()\n\ndef increment():\n    global counter\n    for _ in range(100000):\n        with lock:\n            counter += 1\n\nthreads = [threading.Thread(target=increment) for _ in range(4)]\nfor t in threads: t.start()\nfor t in threads: t.join()\nprint(counter)  # 400000 (dogru!)\n```\n\nAlternatif: threading.atomic veya queue.Queue kullan."
    },
    {
        "instruction": "Bu kodda off-by-one hatasi var:\n```python\ndef binary_search(arr, target):\n    left, right = 0, len(arr)\n    while left < right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid\n        else:\n            right = mid\n    return -1\n```",
        "response": "Iki hata var:\n\n1. right = len(arr) olmali len(arr) - 1\n2. left = mid sonsuz donguye neden olur, left = mid + 1 olmali\n\nDuzeltilmis:\n```python\ndef binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n```\n\nBest practice: Binary search'te sinir degerlerini her zaman dikkatli kontrol et."
    },
    {
        "instruction": "Bu kodda deadlock var:\n```python\nlock_a = threading.Lock()\nlock_b = threading.Lock()\ndef task1():\n    with lock_a:\n        with lock_b:\n            print(\"task1\")\ndef task2():\n    with lock_b:\n        with lock_a:\n            print(\"task2\")\n```",
        "response": "Deadlock! task1 lock_a'yi alip lock_b'yi bekliyor, task2 lock_b'yi alip lock_a'yi bekliyor. Ikisi de birbirini bekler, program donar.\n\nDuzeltme - Her zaman ayni sirada kilitle:\n```python\ndef task1():\n    with lock_a:\n        with lock_b:\n            print(\"task1\")\n\ndef task2():\n    with lock_a:  # Ayni sira!\n        with lock_b:\n            print(\"task2\")\n```\n\nAlternatif - timeout ile:\n```python\ndef safe_acquire(lock, timeout=5):\n    if not lock.acquire(timeout=timeout):\n        raise TimeoutError(\"Lock alinamadi\")\n```\n\nBest practice: Lock sirasini her zaman tutarli tut."
    },
    {
        "instruction": "Bu kodda N+1 query problemi var:\n```python\nusers = User.objects.all()\nfor user in users:\n    print(user.profile.bio)\n```",
        "response": "N+1 query problemi! Her user icin ayri bir SQL sorgusu calisiyor. 1000 user = 1001 sorgu!\n\nDuzeltme - select_related kullan:\n```python\n# Django ORM\nusers = User.objects.select_related('profile').all()\nfor user in users:\n    print(user.profile.bio)  # Tek sorgu!\n```\n\nManyToMany icin prefetch_related:\n```python\nusers = User.objects.prefetch_related('groups').all()\nfor user in users:\n    print(user.groups.all())  # 2 sorgu!\n```\n\nBest practice: ORM kullanirken her zaman query sayisini kontrol et. Django Debug Toolbar veya django-silk kullan."
    },
    {
        "instruction": "Bu kodda XSS acigi var:\n```python\n@app.route('/search')\ndef search():\n    query = request.args.get('q', '')\n    return f'<h1>Arama sonuclari: {query}</h1>'\n```",
        "response": "XSS (Cross-Site Scripting) acigi! Kullanici girdisi dogrudan HTML'e ekleniyor. Saldirgan JavaScript kodu enjekte edebilir.\n\nSaldiri: /search?q=<script>alert('hacked')</script>\n\nDuzeltme - HTML escape:\n```python\nfrom markupsafe import escape\n\n@app.route('/search')\ndef search():\n    query = escape(request.args.get('q', ''))\n    return f'<h1>Arama sonuclari: {query}</h1>'\n```\n\nDaha iyi - Template kullan:\n```python\n@app.route('/search')\ndef search():\n    query = request.args.get('q', '')\n    return render_template('search.html', query=query)\n```\n\nJinja2 otomatik escape yapar. Best practice: Kullanici girdisini ASLA dogrudan HTML'e ekleme."
    },
]

# === 3. CLEAN CODE VE REFACTORING (10 ornek) ===
clean_code = [
    {
        "instruction": "Bu kodu refactor et:\n```python\ndef process(data):\n    result = []\n    for item in data:\n        if item['type'] == 'A':\n            if item['value'] > 10:\n                if item['status'] == 'active':\n                    result.append(item['name'])\n    return result\n```",
        "response": "Arrow code anti-pattern! Ic ice if'ler okunabilirligi dusurur.\n\nRefactored:\n```python\ndef is_valid(item):\n    return (\n        item['type'] == 'A'\n        and item['value'] > 10\n        and item['status'] == 'active'\n    )\n\ndef process(data):\n    return [item['name'] for item in data if is_valid(item)]\n```\n\nAvantajlar:\n- is_valid test edilebilir\n- Kosul mantigi ayrilmis (Single Responsibility)\n- Yeni kosullar eklemesi basit"
    },
    {
        "instruction": "SOLID prensiplerini acikla.",
        "response": "SOLID, nesne yonelimli programlamada bes temel tasarim prensibidir.\n\nS - Single Responsibility: Her sinifin tek bir sorumlulugu olmali.\n```python\n# KOTU\nclass User:\n    def save_to_db(self): ...\n    def send_email(self): ...\n\n# IYI\nclass User: ...\nclass UserRepository:\n    def save(self, user): ...\nclass EmailService:\n    def send(self, user, msg): ...\n```\n\nO - Open/Closed: Genislemeye acik, degisime kapali.\nL - Liskov Substitution: Alt siniflar ust siniflarin yerine kullanilabilmeli.\nI - Interface Segregation: Kullanilmayan metotlara bagimli olunmamali.\nD - Dependency Inversion: Ust seviye moduller alt seviye modullere bagimli olmamali.\n\n```python\nclass Database(ABC):\n    @abstractmethod\n    def query(self, sql): pass\n\nclass UserService:\n    def __init__(self, db: Database):\n        self.db = db  # Dependency injection\n```"
    },
    {
        "instruction": "DRY prensibi nedir?",
        "response": "DRY (Don't Repeat Yourself), kod tekrarindan kacinma prensibidir. Ayni mantik birden fazla yerde tekrarlanmamalidir.\n\nKOTU - tekrar eden kod:\n```python\ndef validate_email(email):\n    if not email:\n        raise ValueError(\"Email bos olamaz\")\n    if '@' not in email:\n        raise ValueError(\"Gecersiz email\")\n\ndef validate_username(username):\n    if not username:\n        raise ValueError(\"Username bos olamaz\")\n    if len(username) < 3:\n        raise ValueError(\"Username cok kisa\")\n```\n\nIYI - ortak mantik ayrilmis:\n```python\ndef validate_required(value, field_name):\n    if not value:\n        raise ValueError(f\"{field_name} bos olamaz\")\n\ndef validate_email(email):\n    validate_required(email, \"Email\")\n    if '@' not in email:\n        raise ValueError(\"Gecersiz email\")\n\ndef validate_username(username):\n    validate_required(username, \"Username\")\n    if len(username) < 3:\n        raise ValueError(\"Username cok kisa\")\n```\n\nDRY sadece kod degil, bilgi tekrari icin de gecerlidir."
    },
    {
        "instruction": "Design patterns nedir? En cok kullanilan 3 tanesini acikla.",
        "response": "Design patterns, yazilim gelistirmede tekrar eden problemlere kanitmis cozumlerdir.\n\n1. Singleton Pattern:\nBir siniftan sadece bir instance olusturulmasini saglar.\n```python\nclass Database:\n    _instance = None\n    \n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n\ndb1 = Database()\ndb2 = Database()\nprint(db1 is db2)  # True\n```\n\n2. Observer Pattern:\nBir nesne degistiginde bagli nesneleri otomatik bilgilendirir.\n```python\nclass EventEmitter:\n    def __init__(self):\n        self._listeners = {}\n    \n    def on(self, event, callback):\n        self._listeners.setdefault(event, []).append(callback)\n    \n    def emit(self, event, *args):\n        for cb in self._listeners.get(event, []):\n            cb(*args)\n```\n\n3. Factory Pattern:\nNesne olusturma mantigi ayri bir sinifta tutulur.\n```python\nclass AnimalFactory:\n    @staticmethod\n    def create(animal_type):\n        if animal_type == \"dog\":\n            return Dog()\n        elif animal_type == \"cat\":\n            return Cat()\n        raise ValueError(f\"Bilinmeyen hayvan: {animal_type}\")\n```"
    },
    {
        "instruction": "Python'da type hints nasil kullanilir?",
        "response": "Type hints, degisken ve fonksiyon tiplerini belirtmek icin kullanilir. Python 3.5+ ile gelmistir.\n\nTemel kullanim:\n```python\ndef greet(name: str) -> str:\n    return f\"Merhaba {name}\"\n\ndef add(a: int, b: int) -> int:\n    return a + b\n```\n\nKoleksiyon tipleri:\n```python\nfrom typing import List, Dict, Optional, Tuple\n\ndef process(items: List[str]) -> Dict[str, int]:\n    return {item: len(item) for item in items}\n\ndef find_user(user_id: int) -> Optional[str]:\n    # None donebilir\n    return users.get(user_id)\n```\n\nPython 3.10+ ile daha temiz:\n```python\ndef process(items: list[str]) -> dict[str, int]:\n    return {item: len(item) for item in items}\n\ndef find(id: int) -> str | None:\n    return data.get(id)\n```\n\nAvantajlar:\n- IDE'den daha iyi otomatik tamamlama\n- mypy ile statik tip kontrolu\n- Kodun okunabilirligi artar"
    },
    {
        "instruction": "Python'da testing nasil yapilir? pytest acikla.",
        "response": "pytest, Python'da en populer test framework'udur.\n\nKurulum: pip install pytest\n\nBasit test:\n```python\n# test_calculator.py\ndef add(a, b):\n    return a + b\n\ndef test_add():\n    assert add(2, 3) == 5\n    assert add(-1, 1) == 0\n    assert add(0, 0) == 0\n```\n\nCalistirma: pytest test_calculator.py\n\nFixture kullanimi:\n```python\nimport pytest\n\n@pytest.fixture\ndef sample_data():\n    return [1, 2, 3, 4, 5]\n\ndef test_sum(sample_data):\n    assert sum(sample_data) == 15\n\ndef test_length(sample_data):\n    assert len(sample_data) == 5\n```\n\nParametrize:\n```python\n@pytest.mark.parametrize(\"input,expected\", [\n    (1, 1),\n    (2, 4),\n    (3, 9),\n])\ndef test_square(input, expected):\n    assert input ** 2 == expected\n```\n\nException testi:\n```python\ndef test_division_by_zero():\n    with pytest.raises(ZeroDivisionError):\n        1 / 0\n```\n\nBest practice: Her fonksiyon icin en az 3 test yaz (normal, sinir, hata durumu)."
    },
    {
        "instruction": "Python'da logging nasil yapilir?",
        "response": "Python'da logging modulu, print yerine kullanilmasi gereken profesyonel loglama aracidir.\n\nTemel kullanim:\n```python\nimport logging\n\nlogging.basicConfig(\n    level=logging.INFO,\n    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'\n)\n\nlogger = logging.getLogger(__name__)\n\nlogger.debug(\"Debug mesaji\")\nlogger.info(\"Bilgi mesaji\")\nlogger.warning(\"Uyari mesaji\")\nlogger.error(\"Hata mesaji\")\nlogger.critical(\"Kritik hata\")\n```\n\nDosyaya loglama:\n```python\nlogging.basicConfig(\n    filename='app.log',\n    level=logging.INFO,\n    format='%(asctime)s - %(levelname)s - %(message)s'\n)\n```\n\nNeden print degil logging?\n- Seviye kontrolu (DEBUG, INFO, WARNING, ERROR)\n- Dosyaya yazma\n- Format kontrolu\n- Moduller arasi tutarlilik\n- Production'da kolayca kapatilabilir"
    },
    {
        "instruction": "Python'da virtual environment neden kullanilir?",
        "response": "Virtual environment, projelerin bagimliklarini izole etmek icin kullanilir.\n\nNeden gerekli?\n- Proje A: Django 3.2 istiyor\n- Proje B: Django 4.2 istiyor\n- Global kurulum ikisini birden karsulayamaz!\n\nOlusturma:\n```bash\npython -m venv .venv\n```\n\nAktivasyonlar:\n```bash\n# Windows PowerShell\n.venv\\Scripts\\activate\n\n# Mac/Linux\nsource .venv/bin/activate\n\n# Git Bash\nsource .venv/Scripts/activate\n```\n\nKullanim:\n```bash\n(.venv) pip install django==4.2\n(.venv) pip freeze > requirements.txt\n(.venv) deactivate\n```\n\nBaska bir bilgisayarda ayni ortami kurma:\n```bash\npython -m venv .venv\n.venv\\Scripts\\activate\npip install -r requirements.txt\n```\n\nBest practice:\n- Her proje icin ayri venv olustur\n- .venv klasorunu .gitignore'a ekle\n- requirements.txt'i her zaman guncelle"
    },
    {
        "instruction": "Git workflow nedir? Feature branch nasil kullanilir?",
        "response": "Git workflow, takim calismasinda kod yonetimi icin kullanilan bir stratejidir.\n\nTemel Git workflow:\n```bash\n# 1. Yeni branch olustur\ngit checkout -b feature/user-login\n\n# 2. Kod yaz, commit et\ngit add .\ngit commit -m \"Add user login feature\"\n\n# 3. Push et\ngit push origin feature/user-login\n\n# 4. Pull Request olustur (GitHub'da)\n\n# 5. Code review sonrasi merge et\ngit checkout main\ngit merge feature/user-login\n\n# 6. Branch'i sil\ngit branch -d feature/user-login\n```\n\nCommit mesaji kurallari:\n```\nfeat: yeni ozellik eklendi\nfix: hata duzeltildi\ndocs: dokumantasyon guncellendi\nrefactor: kod yeniden duzenlendi\ntest: test eklendi\n```\n\nBest practice:\n- main branch her zaman calisir durumda olmali\n- Her ozellik icin ayri branch\n- Kucuk, sik commit'ler yap\n- Anlamli commit mesajlari yaz"
    },
    {
        "instruction": "REST API tasarim prensipleri nelerdir?",
        "response": "REST API, web servisleri icin standart bir mimari tarzidir.\n\nTemel prensipler:\n\n1. URL'ler kaynaklari temsil eder (fiil degil isim):\n```\nIYI:  GET /users, POST /users, GET /users/1\nKOTU: GET /getUsers, POST /createUser\n```\n\n2. HTTP metotlari dogru kullanilir:\n```\nGET    /users      -> Tum kullanicilari getir\nGET    /users/1    -> Tek kullaniciyi getir\nPOST   /users      -> Yeni kullanici olustur\nPUT    /users/1    -> Kullaniciyi guncelle\nDELETE /users/1    -> Kullaniciyi sil\n```\n\n3. Dogru HTTP status kodlari:\n```\n200 OK           -> Basarili\n201 Created      -> Olusturuldu\n400 Bad Request  -> Gecersiz istek\n401 Unauthorized -> Yetki yok\n404 Not Found    -> Bulunamadi\n500 Server Error -> Sunucu hatasi\n```\n\n4. Pagination:\n```\nGET /users?page=2&per_page=20\n```\n\n5. Versioning:\n```\nGET /api/v1/users\nGET /api/v2/users\n```\n\nBest practice: API'ni once tasarla, sonra kodla."
    },
]

# === 4. FRAMEWORK ORNEKLERI (10 ornek) ===
frameworks = [
    {
        "instruction": "FastAPI ile basit bir CRUD API yaz.",
        "response": "FastAPI, modern Python web framework'udur.\n\nKurulum: pip install fastapi uvicorn\n\n```python\nfrom fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\nfrom typing import Optional\n\napp = FastAPI(title=\"Todo API\")\n\nclass Todo(BaseModel):\n    title: str\n    description: Optional[str] = None\n    completed: bool = False\n\ntodos = {}\ncounter = 0\n\n@app.post(\"/todos/\")\nasync def create_todo(todo: Todo):\n    global counter\n    counter += 1\n    todos[counter] = todo.model_dump()\n    todos[counter][\"id\"] = counter\n    return todos[counter]\n\n@app.get(\"/todos/\")\nasync def get_todos():\n    return list(todos.values())\n\n@app.get(\"/todos/{todo_id}\")\nasync def get_todo(todo_id: int):\n    if todo_id not in todos:\n        raise HTTPException(status_code=404)\n    return todos[todo_id]\n\n@app.delete(\"/todos/{todo_id}\")\nasync def delete_todo(todo_id: int):\n    if todo_id not in todos:\n        raise HTTPException(status_code=404)\n    return todos.pop(todo_id)\n```\n\nCalistirma: uvicorn main:app --reload\nDokumantasyon: http://localhost:8000/docs"
    },
    {
        "instruction": "React'te useEffect hook'u nasil calisir?",
        "response": "useEffect, React fonksiyonel bilesenlerinde yan etkileri yonetmek icin kullanilir.\n\n1. Her renderda:\n```jsx\nuseEffect(() => {\n    console.log(\"Her renderda\");\n});\n```\n\n2. Sadece mount'ta (bos dizi):\n```jsx\nuseEffect(() => {\n    fetchData();\n}, []);\n```\n\n3. Belirli deger degistiginde:\n```jsx\nuseEffect(() => {\n    document.title = `Count: ${count}`;\n}, [count]);\n```\n\n4. Cleanup:\n```jsx\nuseEffect(() => {\n    const timer = setInterval(() => console.log(\"tick\"), 1000);\n    return () => clearInterval(timer);\n}, []);\n```\n\nYaygin hatalar:\n- Bagimlilik dizisini unutmak (sonsuz dongu)\n- Cleanup yapmamak (memory leak)"
    },
    {
        "instruction": "Docker nedir? Dockerfile nasil yazilir?",
        "response": "Docker, uygulamalari container'lar icinde calistirarak ortam bagimliligini ortadan kaldirir.\n\nTemel Dockerfile:\n```dockerfile\n# Python uygulamasi icin\nFROM python:3.11-slim\n\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nCOPY . .\n\nEXPOSE 8000\n\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n```\n\nDocker Compose:\n```yaml\nversion: '3.8'\nservices:\n  web:\n    build: .\n    ports:\n      - \"8000:8000\"\n  db:\n    image: postgres:15\n    environment:\n      POSTGRES_PASSWORD: secret\n```\n\nTemel komutlar:\n```bash\ndocker build -t myapp .\ndocker run -p 8000:8000 myapp\ndocker-compose up -d\n```\n\nBest practice:\n- .dockerignore kullan\n- Multi-stage build ile image boyutunu kucult\n- Root kullanici kullanma"
    },
    {
        "instruction": "SQLAlchemy ORM nasil kullanilir?",
        "response": "SQLAlchemy, Python'un en populer ORM kutuphanesidir.\n\nKurulum: pip install sqlalchemy\n\n```python\nfrom sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base, sessionmaker\n\nBase = declarative_base()\n\nclass User(Base):\n    __tablename__ = 'users'\n    id = Column(Integer, primary_key=True)\n    name = Column(String(50), nullable=False)\n    email = Column(String(100), unique=True)\n\n# Engine ve session\nengine = create_engine('sqlite:///app.db')\nBase.metadata.create_all(engine)\nSession = sessionmaker(bind=engine)\nsession = Session()\n\n# CRUD\nuser = User(name=\"Ali\", email=\"ali@example.com\")\nsession.add(user)\nsession.commit()\n\n# Sorgulama\nusers = session.query(User).filter(User.name == \"Ali\").all()\nuser = session.query(User).get(1)\n\n# Guncelleme\nuser.name = \"Mehmet\"\nsession.commit()\n\n# Silme\nsession.delete(user)\nsession.commit()\n```"
    },
    {
        "instruction": "WebSocket nedir? Python'da nasil kullanilir?",
        "response": "WebSocket, istemci ve sunucu arasinda cift yonlu, gercek zamanli iletisim saglar. HTTP'den farki: baglanti surekli acik kalir.\n\nKullanim alanlari: Chat, canli bildirim, oyun, borsa\n\nSunucu (FastAPI + WebSocket):\n```python\nfrom fastapi import FastAPI, WebSocket\n\napp = FastAPI()\nclients = []\n\n@app.websocket(\"/ws\")\nasync def websocket_endpoint(websocket: WebSocket):\n    await websocket.accept()\n    clients.append(websocket)\n    try:\n        while True:\n            data = await websocket.receive_text()\n            for client in clients:\n                await client.send_text(f\"Mesaj: {data}\")\n    except:\n        clients.remove(websocket)\n```\n\nIstemci (JavaScript):\n```javascript\nconst ws = new WebSocket('ws://localhost:8000/ws');\n\nws.onopen = () => ws.send('Merhaba!');\nws.onmessage = (event) => console.log(event.data);\nws.onclose = () => console.log('Baglanti kapandi');\n```"
    },
    {
        "instruction": "Redis nedir? Python'da nasil kullanilir?",
        "response": "Redis, bellek ici (in-memory) key-value veritabanidir. Cache, session, queue icin kullanilir.\n\nKurulum: pip install redis\n\n```python\nimport redis\n\nr = redis.Redis(host='localhost', port=6379, db=0)\n\n# String\nr.set('name', 'Ali')\nprint(r.get('name'))  # b'Ali'\n\n# TTL (sure sinirli)\nr.setex('token', 3600, 'abc123')  # 1 saat\n\n# Hash\nr.hset('user:1', mapping={'name': 'Ali', 'age': 25})\nprint(r.hgetall('user:1'))\n\n# List\nr.rpush('queue', 'task1', 'task2')\ntask = r.lpop('queue')  # FIFO\n\n# Set\nr.sadd('tags', 'python', 'redis', 'cache')\nprint(r.smembers('tags'))\n```\n\nCache ornegi:\n```python\nimport json\n\ndef get_user(user_id):\n    cached = r.get(f'user:{user_id}')\n    if cached:\n        return json.loads(cached)\n    user = db.query(User).get(user_id)\n    r.setex(f'user:{user_id}', 300, json.dumps(user))\n    return user\n```\n\nBest practice: Cache invalidation stratejisi belirle."
    },
    {
        "instruction": "GraphQL nedir? REST'ten farki ne?",
        "response": "GraphQL, Facebook tarafindan gelistirilen bir API sorgu dilidir.\n\nREST vs GraphQL:\n```\nREST: Sunucu ne verirse onu alirsin\nGET /users/1 -> {id, name, email, address, phone, ...}\n\nGraphQL: Ne istersen onu alirsin\nquery { user(id: 1) { name, email } }\n```\n\nPython'da (Strawberry):\n```python\nimport strawberry\nfrom fastapi import FastAPI\nfrom strawberry.fastapi import GraphQLRouter\n\n@strawberry.type\nclass User:\n    name: str\n    age: int\n\n@strawberry.type\nclass Query:\n    @strawberry.field\n    def user(self, id: int) -> User:\n        return User(name=\"Ali\", age=25)\n\nschema = strawberry.Schema(query=Query)\napp = FastAPI()\napp.include_router(GraphQLRouter(schema), prefix=\"/graphql\")\n```\n\nNe zaman GraphQL?\n- Mobil uygulamalar (bant genisligi tasarrufu)\n- Karmasik veri iliskileri\n- Frontend'in farkli veri ihtiyaclari\n\nNe zaman REST?\n- Basit CRUD\n- Cache'leme onemli\n- Dosya yukleme/indirme"
    },
    {
        "instruction": "CI/CD nedir? GitHub Actions nasil kullanilir?",
        "response": "CI/CD, kodun otomatik test edilmesi ve dagitilmasini saglar.\n\nCI = Continuous Integration: Her commit'te otomatik test\nCD = Continuous Deployment: Testler gecerse otomatik dagitim\n\nGitHub Actions ornegi (.github/workflows/ci.yml):\n```yaml\nname: CI\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.11'\n      - run: pip install -r requirements.txt\n      - run: pytest tests/ -v\n\n  deploy:\n    needs: test\n    runs-on: ubuntu-latest\n    if: github.ref == 'refs/heads/main'\n    steps:\n      - uses: actions/checkout@v4\n      - run: echo \"Deploy to production\"\n```\n\nBest practice:\n- Her PR'da testler calissin\n- main branch'e direkt push yapma\n- Linting ve formatting kontrolleri ekle"
    },
    {
        "instruction": "Python'da multiprocessing nasil kullanilir?",
        "response": "Multiprocessing, CPU-yogun islemleri paralel calistirmak icin kullanilir. GIL'i bypass eder.\n\n```python\nfrom multiprocessing import Pool\nimport time\n\ndef heavy_task(n):\n    total = sum(i*i for i in range(n))\n    return total\n\nif __name__ == '__main__':\n    numbers = [10_000_000] * 4\n    \n    # Seri calistirma\n    start = time.time()\n    results = [heavy_task(n) for n in numbers]\n    print(f\"Seri: {time.time()-start:.2f}s\")\n    \n    # Paralel calistirma\n    start = time.time()\n    with Pool(4) as p:\n        results = p.map(heavy_task, numbers)\n    print(f\"Paralel: {time.time()-start:.2f}s\")\n```\n\nNe zaman multiprocessing?\n- CPU-yogun islemler (hesaplama, resim isleme)\n- GIL sinirlama yapiyorsa\n\nNe zaman threading?\n- I/O-yogun islemler (dosya, network)\n\nNe zaman asyncio?\n- Cok sayida I/O islemi (web scraping, API)"
    },
    {
        "instruction": "Python'da ORM yerine raw SQL ne zaman kullanilir?",
        "response": "ORM her durumda ideal degildir. Bazi durumlarda raw SQL daha uygun.\n\nORM kullan:\n- Basit CRUD islemleri\n- Hizli gelistirme\n- Veritabani bagimsizligi gerektiginde\n\nRaw SQL kullan:\n- Karmasik sorgular (window functions, CTE)\n- Performans kritik sorgular\n- Bulk islemler\n- Veritabanina ozgu ozellikler\n\nOrnek - ORM'in zorlastigi sorgu:\n```python\n# Raw SQL (daha okunabilir)\nquery = \"\"\"\n    WITH monthly_sales AS (\n        SELECT \n            DATE_TRUNC('month', created_at) as month,\n            SUM(amount) as total\n        FROM orders\n        GROUP BY 1\n    )\n    SELECT month, total,\n           LAG(total) OVER (ORDER BY month) as prev_month,\n           total - LAG(total) OVER (ORDER BY month) as growth\n    FROM monthly_sales\n    ORDER BY month\n\"\"\"\n\nresults = session.execute(text(query)).fetchall()\n```\n\nBest practice: ORM ile basla, performans gerektirdiginde raw SQL'e gec. Her ikisini de bilmek onemli."
    },
]

# === 5. ALGORITMA VE VERI YAPILARI (10 ornek) ===
algorithms = [
    {
        "instruction": "Binary search algoritmasi acikla ve yaz.",
        "response": "Binary search, sirali dizide O(log n) zamanda arama yapar.\n\n```python\ndef binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1\n\nnumbers = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91]\nprint(binary_search(numbers, 23))  # 5\n```\n\nZaman karmasikligi: O(log n)\nOnemli: Sadece SIRALI dizilerde calisir!"
    },
    {
        "instruction": "Hash table nasil calisir?",
        "response": "Hash table, anahtar-deger ciftlerini O(1) ortalama surede saklar.\n\n```python\nclass HashTable:\n    def __init__(self, size=10):\n        self.size = size\n        self.table = [[] for _ in range(size)]\n    \n    def _hash(self, key):\n        return hash(key) % self.size\n    \n    def put(self, key, value):\n        index = self._hash(key)\n        bucket = self.table[index]\n        for i, (k, v) in enumerate(bucket):\n            if k == key:\n                bucket[i] = (key, value)\n                return\n        bucket.append((key, value))\n    \n    def get(self, key):\n        index = self._hash(key)\n        for k, v in self.table[index]:\n            if k == key:\n                return v\n        raise KeyError(key)\n\nht = HashTable()\nht.put(\"name\", \"Ali\")\nprint(ht.get(\"name\"))  # Ali\n```"
    },
    {
        "instruction": "Stack ve Queue veri yapilarini acikla.",
        "response": "Stack (Yigin): LIFO - Son giren ilk cikar\nQueue (Kuyruk): FIFO - Ilk giren ilk cikar\n\nStack:\n```python\nclass Stack:\n    def __init__(self):\n        self._items = []\n    \n    def push(self, item):\n        self._items.append(item)\n    \n    def pop(self):\n        if self.is_empty():\n            raise IndexError(\"Stack bos\")\n        return self._items.pop()\n    \n    def peek(self):\n        return self._items[-1]\n    \n    def is_empty(self):\n        return len(self._items) == 0\n```\n\nQueue:\n```python\nfrom collections import deque\n\nclass Queue:\n    def __init__(self):\n        self._items = deque()\n    \n    def enqueue(self, item):\n        self._items.append(item)\n    \n    def dequeue(self):\n        if self.is_empty():\n            raise IndexError(\"Queue bos\")\n        return self._items.popleft()\n    \n    def is_empty(self):\n        return len(self._items) == 0\n```\n\nKullanim alanlari:\n- Stack: Undo/redo, parantez eslestirme, DFS\n- Queue: BFS, task queue, printer queue"
    },
    {
        "instruction": "Big O notasyonu nedir? Orneklerle acikla.",
        "response": "Big O, bir algoritmanin zaman veya alan karmasikligini ifade eder.\n\nYaygin karmasikliklar (en iyiden en kotuye):\n\nO(1) - Sabit:\n```python\ndef get_first(arr):\n    return arr[0]  # Her zaman 1 islem\n```\n\nO(log n) - Logaritmik:\n```python\ndef binary_search(arr, target):  # Her adimda yarilanir\n    ...\n```\n\nO(n) - Lineer:\n```python\ndef find_max(arr):\n    max_val = arr[0]\n    for num in arr:  # n eleman gezilir\n        if num > max_val:\n            max_val = num\n    return max_val\n```\n\nO(n log n) - Log-lineer:\n```python\nsorted(arr)  # Merge sort, timsort\n```\n\nO(n^2) - Karesel:\n```python\ndef bubble_sort(arr):\n    for i in range(len(arr)):      # n kez\n        for j in range(len(arr)):  # n kez\n            ...  # n * n = n^2\n```\n\nO(2^n) - Ustel:\n```python\ndef fibonacci(n):  # Her cagri 2 cagri yapar\n    if n < 2: return n\n    return fibonacci(n-1) + fibonacci(n-2)\n```\n\nPratik kural: n=1000 icin O(n^2) yavaslar, O(n log n) hizli kalir."
    },
    {
        "instruction": "Linked list nedir? Python'da yaz.",
        "response": "Linked list, her elemanin bir sonraki elemana isaretci tuttugu veri yapisidir.\n\n```python\nclass Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None\n\nclass LinkedList:\n    def __init__(self):\n        self.head = None\n    \n    def append(self, data):\n        new_node = Node(data)\n        if not self.head:\n            self.head = new_node\n            return\n        current = self.head\n        while current.next:\n            current = current.next\n        current.next = new_node\n    \n    def prepend(self, data):\n        new_node = Node(data)\n        new_node.next = self.head\n        self.head = new_node\n    \n    def delete(self, data):\n        if not self.head:\n            return\n        if self.head.data == data:\n            self.head = self.head.next\n            return\n        current = self.head\n        while current.next:\n            if current.next.data == data:\n                current.next = current.next.next\n                return\n            current = current.next\n    \n    def display(self):\n        elements = []\n        current = self.head\n        while current:\n            elements.append(str(current.data))\n            current = current.next\n        print(\" -> \".join(elements) + \" -> None\")\n\nll = LinkedList()\nll.append(1)\nll.append(2)\nll.append(3)\nll.display()  # 1 -> 2 -> 3 -> None\n```\n\nArray vs LinkedList:\n- Array: O(1) erisim, O(n) ekleme/silme\n- LinkedList: O(n) erisim, O(1) ekleme/silme (basta)"
    },
    {
        "instruction": "Graph veri yapisi nedir? BFS ve DFS acikla.",
        "response": "Graph, dugumler (nodes) ve kenarlardan (edges) olusan veri yapisidir.\n\n```python\nclass Graph:\n    def __init__(self):\n        self.adjacency_list = {}\n    \n    def add_vertex(self, vertex):\n        if vertex not in self.adjacency_list:\n            self.adjacency_list[vertex] = []\n    \n    def add_edge(self, v1, v2):\n        self.adjacency_list[v1].append(v2)\n        self.adjacency_list[v2].append(v1)\n```\n\nBFS (Breadth-First Search) - Genislik oncelikli:\n```python\nfrom collections import deque\n\ndef bfs(graph, start):\n    visited = set()\n    queue = deque([start])\n    visited.add(start)\n    \n    while queue:\n        vertex = queue.popleft()\n        print(vertex, end=\" \")\n        for neighbor in graph[vertex]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n```\n\nDFS (Depth-First Search) - Derinlik oncelikli:\n```python\ndef dfs(graph, start, visited=None):\n    if visited is None:\n        visited = set()\n    visited.add(start)\n    print(start, end=\" \")\n    for neighbor in graph[start]:\n        if neighbor not in visited:\n            dfs(graph, neighbor, visited)\n```\n\nNe zaman BFS? En kisa yol bulma\nNe zaman DFS? Tum yollari arama, cycle detection"
    },
    {
        "instruction": "Sorting algoritmalari karsilastirmasi yap.",
        "response": "Python'da yaygin siralama algoritmalari:\n\n1. Bubble Sort - O(n^2):\n```python\ndef bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n-i-1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n```\n\n2. Merge Sort - O(n log n):\n```python\ndef merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n```\n\n3. Quick Sort - O(n log n) ortalama:\n```python\ndef quick_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr)//2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quick_sort(left) + middle + quick_sort(right)\n```\n\nKarsilastirma:\n- Bubble: O(n^2), basit, kucuk diziler icin\n- Merge: O(n log n), stabil, ekstra bellek\n- Quick: O(n log n) ort., yerinde, en hizli pratikte\n- Python sorted(): Timsort, O(n log n), en iyi secim"
    },
    {
        "instruction": "Dynamic programming nedir? Ornekle acikla.",
        "response": "Dynamic programming (DP), buyuk problemi kucuk alt problemlere bolup cozme tekniigidir. Her alt problem bir kez cozulur ve sonuc saklanir.\n\nKlasik ornek - Fibonacci:\n```python\n# KOTU - O(2^n) tekrar hesaplama\ndef fib_recursive(n):\n    if n < 2: return n\n    return fib_recursive(n-1) + fib_recursive(n-2)\n\n# IYI - Top-down (memoization) O(n)\ndef fib_memo(n, memo={}):\n    if n in memo: return memo[n]\n    if n < 2: return n\n    memo[n] = fib_memo(n-1) + fib_memo(n-2)\n    return memo[n]\n\n# IYI - Bottom-up (tabulation) O(n)\ndef fib_dp(n):\n    if n < 2: return n\n    dp = [0] * (n + 1)\n    dp[1] = 1\n    for i in range(2, n + 1):\n        dp[i] = dp[i-1] + dp[i-2]\n    return dp[n]\n```\n\nKlasik ornek - Knapsack (Sirt cantasi):\n```python\ndef knapsack(weights, values, capacity):\n    n = len(weights)\n    dp = [[0] * (capacity + 1) for _ in range(n + 1)]\n    \n    for i in range(1, n + 1):\n        for w in range(capacity + 1):\n            if weights[i-1] <= w:\n                dp[i][w] = max(\n                    dp[i-1][w],\n                    dp[i-1][w-weights[i-1]] + values[i-1]\n                )\n            else:\n                dp[i][w] = dp[i-1][w]\n    \n    return dp[n][capacity]\n```\n\nDP ne zaman kullanilir?\n- Overlapping subproblems (tekrar eden alt problemler)\n- Optimal substructure (optimal cozum alt cozumlerden olusur)"
    },
    {
        "instruction": "Tree veri yapisi nedir? Binary search tree yaz.",
        "response": "Tree, hiyerarsik veri yapisidir. Her dugumun cocuklari vardir. Binary tree'de her dugumun en fazla 2 cocugu olur.\n\n```python\nclass TreeNode:\n    def __init__(self, value):\n        self.value = value\n        self.left = None\n        self.right = None\n\nclass BinarySearchTree:\n    def __init__(self):\n        self.root = None\n    \n    def insert(self, value):\n        if not self.root:\n            self.root = TreeNode(value)\n        else:\n            self._insert(self.root, value)\n    \n    def _insert(self, node, value):\n        if value < node.value:\n            if node.left is None:\n                node.left = TreeNode(value)\n            else:\n                self._insert(node.left, value)\n        else:\n            if node.right is None:\n                node.right = TreeNode(value)\n            else:\n                self._insert(node.right, value)\n    \n    def search(self, value):\n        return self._search(self.root, value)\n    \n    def _search(self, node, value):\n        if node is None:\n            return False\n        if value == node.value:\n            return True\n        elif value < node.value:\n            return self._search(node.left, value)\n        else:\n            return self._search(node.right, value)\n    \n    def inorder(self, node=None, first=True):\n        if first:\n            node = self.root\n        if node:\n            self.inorder(node.left, False)\n            print(node.value, end=\" \")\n            self.inorder(node.right, False)\n\nbst = BinarySearchTree()\nfor val in [5, 3, 7, 1, 4, 6, 8]:\n    bst.insert(val)\nbst.inorder()  # 1 3 4 5 6 7 8\n```\n\nZaman karmasikligi (ortalama): O(log n) arama, ekleme, silme"
    },
    {
        "instruction": "Heap veri yapisi nedir?",
        "response": "Heap, oncelik kuyrugu (priority queue) icin kullanilan agac yapisidadir. Min-heap'te en kucuk eleman her zaman koke yakindir.\n\nPython'da heapq modulu:\n```python\nimport heapq\n\n# Min-heap\nnumbers = [5, 3, 8, 1, 9, 2]\nheapq.heapify(numbers)\nprint(numbers)  # [1, 3, 2, 5, 9, 8]\n\n# En kucuk elemani cikar\nsmallest = heapq.heappop(numbers)  # 1\n\n# Eleman ekle\nheapq.heappush(numbers, 0)\n\n# En kucuk n eleman\ntop_3 = heapq.nsmallest(3, numbers)\n```\n\nMax-heap (negatif degerlerle):\n```python\nmax_heap = []\nfor num in [5, 3, 8, 1, 9]:\n    heapq.heappush(max_heap, -num)\n\nlargest = -heapq.heappop(max_heap)  # 9\n```\n\nKullanim alanlari:\n- K. en buyuk/kucuk eleman bulma\n- Dijkstra algoritmasi\n- Task scheduling\n- Median bulma (iki heap ile)\n\nZaman: O(log n) ekleme/cikarma, O(1) min/max erisim"
    },
]

# === HEPSINI BIRLESTIR ===
for item in code_explanations:
    data.append(item)
for item in bug_fixes:
    data.append(item)
for item in clean_code:
    data.append(item)
for item in frameworks:
    data.append(item)
for item in algorithms:
    data.append(item)

# Augmentation - veriyi cogalt
random.seed(42)
augmented = []
for _ in range(80):
    shuffled = data.copy()
    random.shuffle(shuffled)
    augmented.extend(shuffled)

print(f"Orijinal ornek: {len(data)}")
print(f"Augmented ornek: {len(augmented)}")

# Orijinal veriyi kaydet
with open('training_data.json', 'w', encoding='utf-8') as f:
    json.dump(augmented, f, ensure_ascii=False, indent=2)

print("training_data.json kaydedildi!")
print(f"Dosya boyutu: yaklasik {len(json.dumps(augmented, ensure_ascii=False)) / 1024:.1f} KB")